apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../default
- ../samples
- ../scorecard

images:
- name: controller
  newName: quay.io/submariner/submariner-operator
  newTag: feature-multi-active-gw-237d98b
- name: repo
  newName: quay.io/submariner
